sudo: required
services:
  - docker

before_install:
  - docker build -t viveknum/docker-react -f Dockerfile.dev .
  
script:
  - docker run   viveknum/docker-react CI=true npm run test --watchAll=false
